services:
  storycast:
    build: .
    container_name: storycast
    ports:
      - "6500:8080"
    volumes:
      - storycast_data:/data
    environment:
      DATA_DIR: /data
      DEFAULT_VOICE: en-US-AriaNeural
      MAX_UPLOAD_FILES: 100
      MAX_TOTAL_CHARS: 1000000
      MAX_CHARS_PER_CHUNK: 4500
      MAX_CONCURRENT_JOBS: 1
    restart: unless-stopped
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.7

volumes:
  storycast_data:

networks:
  npm_proxy:
    external: true