services:
  storycast:
    image: gdunn03/storycast:latest
    container_name: storycast
    volumes:
      - storycast_data:/data
    environment:
      DATA_DIR: /data
      DEFAULT_VOICE: en-US-AriaNeural
      MAX_UPLOAD_FILES: 100
      MAX_TOTAL_CHARS: 1000000
      MAX_CHARS_PER_CHUNK: 4500
      MAX_CONCURRENT_JOBS: 1
    restart: unless-stopped
    networks:
      np_proxy:
        ipv4_address: 192.168.89.7

volumes:
  storycast_data:

networks:
  np_proxy:
    external: true